name: ci
on:
  push:
    branches:
      - 'trunk'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: joaquinomgame
          password: 3046007f-46b0-4772-bb4c-d07669a6c51b
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: joaquinomgame/rboxlo:latest
